CREATE TABLE `project_audit_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`entityType` varchar(64) NOT NULL,
	`entityId` int,
	`action` varchar(64) NOT NULL,
	`fieldName` varchar(128),
	`oldValue` text,
	`newValue` text,
	`reason` text,
	`performedBy` varchar(120) NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `project_audit_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `project_delay_ledger` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`movementId` int,
	`delayDate` date NOT NULL,
	`delayDays` int NOT NULL,
	`delayCategory` enum('company','client','external') NOT NULL,
	`ownerCode` varchar(64) NOT NULL,
	`responsibleId` int,
	`reasonCode` varchar(96) NOT NULL,
	`notes` text,
	`isHoldPeriod` int NOT NULL DEFAULT 0,
	`createdBy` varchar(120),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `project_delay_ledger_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `project_delay_reasons` (
	`id` int AUTO_INCREMENT NOT NULL,
	`code` varchar(96) NOT NULL,
	`ownerCode` varchar(64) NOT NULL,
	`labelAr` varchar(255) NOT NULL,
	`labelEn` varchar(255),
	`category` enum('company','client','external') NOT NULL DEFAULT 'company',
	`requiresNotes` int NOT NULL DEFAULT 0,
	`isActive` int NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `project_delay_reasons_id` PRIMARY KEY(`id`),
	CONSTRAINT `project_delay_reasons_code_unique` UNIQUE(`code`)
);
--> statement-breakpoint
CREATE TABLE `project_movements` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`stageKey` varchar(64) NOT NULL,
	`stageName` varchar(160) NOT NULL,
	`department` varchar(120) NOT NULL,
	`previousStageKey` varchar(64),
	`previousDepartment` varchar(120),
	`enteredAt` timestamp NOT NULL DEFAULT (now()),
	`plannedCompletionDate` date NOT NULL,
	`actualCompletionDate` timestamp,
	`plannedHandoverDate` date,
	`actualHandoverDate` timestamp,
	`actualReceiptDate` timestamp,
	`slaDays` int NOT NULL,
	`actualDurationDays` int NOT NULL DEFAULT 0,
	`delayDays` int NOT NULL DEFAULT 0,
	`inheritedDelayDays` int NOT NULL DEFAULT 0,
	`generatedDelayDays` int NOT NULL DEFAULT 0,
	`delayOwnerCode` varchar(64),
	`delayResponsibleId` int,
	`delayReasonCode` varchar(96),
	`notes` text,
	`status` enum('active','completed','on_hold') NOT NULL DEFAULT 'active',
	`updatedBy` varchar(120),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `project_movements_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `project_stages` (
	`id` int AUTO_INCREMENT NOT NULL,
	`stageKey` varchar(64) NOT NULL,
	`nameAr` varchar(160) NOT NULL,
	`nameEn` varchar(160),
	`department` varchar(120) NOT NULL,
	`sequence` int NOT NULL,
	`defaultSlaDays` int NOT NULL DEFAULT 3,
	`defaultHandoverDays` int NOT NULL DEFAULT 0,
	`color` varchar(32) DEFAULT '#3B82F6',
	`isActive` int NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `project_stages_id` PRIMARY KEY(`id`),
	CONSTRAINT `project_stages_stageKey_unique` UNIQUE(`stageKey`)
);
--> statement-breakpoint
CREATE TABLE `project_updates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`movementId` int,
	`updateType` enum('status_update','monday_review','wednesday_review','handover','hold','resume') NOT NULL DEFAULT 'status_update',
	`currentStatus` varchar(120),
	`currentStageKey` varchar(64),
	`nextAction` text,
	`expectedCompletionDate` date,
	`hasBlocker` int NOT NULL DEFAULT 0,
	`delayOwnerCode` varchar(64),
	`delayReasonCode` varchar(96),
	`notes` text,
	`updatedBy` varchar(120) NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `project_updates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `projects` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectCode` varchar(64) NOT NULL,
	`dealId` int NOT NULL,
	`clientName` varchar(255) NOT NULL,
	`contractNumber` varchar(120),
	`salesEngineerId` int NOT NULL,
	`contractValue` decimal(14,2) NOT NULL,
	`contractDate` date NOT NULL,
	`agreedDeliveryDate` date,
	`currentStageKey` varchar(64) NOT NULL DEFAULT 'sales',
	`currentDepartment` varchar(120) NOT NULL DEFAULT 'إدارة المبيعات',
	`currentResponsibleId` int,
	`currentStageEnteredAt` timestamp NOT NULL DEFAULT (now()),
	`plannedProjectCompletionDate` date,
	`expectedProjectCompletionDate` date,
	`actualCompletionDate` date,
	`projectStatus` enum('on_time','at_risk','delayed','critical_delay','on_hold','completed','closed') NOT NULL DEFAULT 'on_time',
	`totalDelayDays` int NOT NULL DEFAULT 0,
	`companyDelayDays` int NOT NULL DEFAULT 0,
	`clientDelayDays` int NOT NULL DEFAULT 0,
	`externalDelayDays` int NOT NULL DEFAULT 0,
	`currentStageDelayDays` int NOT NULL DEFAULT 0,
	`inheritedDelayDays` int NOT NULL DEFAULT 0,
	`mainDelayOwnerCode` varchar(64),
	`mainDelayReasonCode` varchar(96),
	`mainDelayResponsibleId` int,
	`nextRequiredAction` text,
	`nextPlannedHandover` date,
	`lastUpdatedAt` timestamp,
	`lastUpdatedBy` varchar(120),
	`updateStatus` enum('up_to_date','missing','not_required') NOT NULL DEFAULT 'missing',
	`isOnHold` int NOT NULL DEFAULT 0,
	`holdStartedAt` timestamp,
	`holdExpectedResumeDate` date,
	`holdOwnerCode` varchar(64),
	`holdReasonCode` varchar(96),
	`holdNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `projects_id` PRIMARY KEY(`id`),
	CONSTRAINT `projects_projectCode_unique` UNIQUE(`projectCode`),
	CONSTRAINT `projects_dealId_unique` UNIQUE(`dealId`)
);
